### ISSUE TITLE
test the psychopy demo for epi netstation

### ISSUE THREAD

**Issue by kschuler** [kschuler/words-in-noise-EEG#24]
make sure it works; figure out how to connect to port

**Comment by kcm1231** [comment]
Hey there,
I got the IP address from Andrei and went down to test it out - instead of "trying to connect to unreachable host" the new error message says "could not connect because host actively denied the connection"

I think this may be because the netstation computer was turned on, but not logged in. I'm going to get some more info from Andrei and try again, just wanted to keep you posted

**Comment by kcm1231** [comment]
Tested it and it worked successfully! We should be able to add in the EEG trigger anywhere in the experiment and it will send an event to the netstation computer.

**Comment by kschuler** [comment]
Awesome, closing issue.
