### ISSUE TITLE
Order of Easy/Hard trials

### ISSUE THREAD

**Issue by kcm1231** [kschuler/words-in-noise-EEG#26]
Hey there,

Right now, the easy/hard trials and randomly mixed within a block. In doing some piloting, we would like to switch this so that easy and hard always alternate. We need to counterbalance (across blocks) whether the block starts with easy or hard, but within the block it should always be one after the other.

That ok?

**Comment by kschuler** [comment]
Yep, sure. I'm sort of off the grid this week.  My job talk / interview at Penn is on Tuesday.  I'm giving two more practice talks this week and generally going on all in on preparing for that (since the stakes are so high!)


However, if you want to test this out, i *THINK* you can change this easily yourself.  There is a small part of the function `build_the_staircase` in which the multi-stair handler is set up.  `self.STAIRCASE_HANDLER` has an attribute called `method` which sets whether the easy and hard staircases are randomized (or not).  Right now it is hard coded as `random` in that it will always randomize the two. If you want it to stop randomizing the blocks, you can set this method to `sequential`.

I *SUSPECT* that the behavior of `sequential` will be to do them in the order they are presented in the conditions file, alternating between each one.  HOWEVER, I haven't tested this, so it could be that it will do all of the Easy first and all of the Hard next, or whatever.  (I don't see how this could be, given how the handler behaves, but it is possible)

Here is the relevant code section.  You'd change `method: random` to `method:sequential` to try this out.  If it works we can move this parameter out of the hard code and into the parameter file so it can be set by that instead (as most other options are).



```    
def build_the_staircases(self, all_staircases):

        # here we build all of the staircases we will use in the experiment.  This is handled by creating a
        # MultiStairHandler for each condition (Auditory, Visual, and Environmental).  Each multistair
        # has an easy and a hard staircase, and they are interleaved (selected at random such that not more than
        # three of the same difficulty level are selected in a row).  All staircases are QUEST adaptive staircases
        # with parameters set from the params.yaml file

        # make an empty dictionary to hold the staircases
        self.STAIRCASE_HANDLER = {}

        # for all of the staircases (in params - baseline and main)
        for staircase in all_staircases:

            # create an empty dictionary
            self.STAIRCASE_HANDLER[staircase] = {}

            # and add a multistair handler for each condition (Auditory, Visual, and Environmental)
            for condition in PARAMS['experiment info']['user-input']['conditions']:
                self.STAIRCASE_HANDLER[staircase].update({condition: data.MultiStairHandler(
                        stairType = 'simple',
                        method = 'random',
                        conditions = [PARAMS['staircases'][staircase][condition]['easy'], PARAMS['staircases'][staircase][condition]['hard']],
                        nTrials = PARAMS['method']['reps'][staircase]['trials per staircase']
                        # name = staircase+" "+condition
                        )})
```

**Comment by kcm1231** [comment]
This worked! Thank you!
